project: 
  type: book
  output-dir: "./../"
  preview:
    watch-inputs: true
    timeout: 5000
    browser: false
    port: 4200

number-sections: false
book:
  chapters:
    - index.qmd # README.qmd
    
    - part: "Documentações"
      chapters:
        - newsroom.qmd

    - part: "Guides"
      chapters:
        - venv.qmd
        - joinrepo.qmd
        - prettier.qmd
        - patterns.qmd

format: 
  html:
    include-in-header: "include-in-head"
    sidebar: true
    search: false
    grid: 
      content-mode: slim 
      