project:
  title: "Introdução a Ciência da Computação"
  type: book
  output-dir: "../../EST0033"
  lib-dir: "../ac/site_libs"
  preview:
    port: 4200
    browser: false
number-sections: false
book:
  title: "Introdução a Ciência da Computação"
  page-navigation: true
  reader-mode: true
  repo-branch: main
  navbar: false
  search: true # Desativado para corrigir path-links-html
  favicon: "ac/image/logo/estatistica.svg"
  chapters:
    - index.qmd
    - conteudo/01/introducao.qmd
    - part: conteudo/02/conclusao.qmd
      chapters: 
        - conteudo/02/metodologia.qmd
        - conteudo/02/conclusao.qmd
    - conteudo/03/references.qmd
    - conteudo/03/apendice.qmd


  page-footer:
    left: |
     Este livro foi desenvolvido por <a href="https://github.com/cesargabrielphd/">César Gabriel</a>
    right: |
      Este book foi construido com <a href="https://quarto.org/">Quarto</a>.

bibliography: conteudo/03/references.bib

format:
  html:
    toc: false
    sidebar: true
    fontfamily: "SF Pro Display"
    fontsize: 12pt
    theme:
      - cosmo
      - brand
      - "../ac/r4ds.scss"
    code-link: true
    author-meta: "César Gabriel"
    callout-appearance: simple
    css: 
      - "/wss/fonts.css?families=SF+Pro,v3"
      - "/ac/site_libs/bootstrap/bootstrap-8da5b4427184b79ecddefad3d342027e.min.css"
      - "/ac/site_libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css"
      - "/ac/site_libs/bootstrap/bootstrap-icons.css"
      - "/ac/site_libs/quarto-html/tippy.css"
    include-in-header: 
      - "/ac/site_libs/bootstrap/bootstrap-8da5b4427184b79ecddefad3d342027e.min.css"
      - "/ac/site_libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css"
      - "/ac/site_libs/bootstrap/bootstrap-icons.css"
      - "/ac/site_libs/quarto-html/tippy.css"
      - "/ac/site_libs/bootstrap/bootstrap-icons.woff"
      - "/ac/site_libs/bootstrap/bootstrap.min.js"
      - "/ac/site_libs/clipboard/clipboard.min.js"
      - "/ac/site_libs/quarto-html/anchor.min.js"
      - "/ac/site_libs/quarto-html/popper.min.js"
      - "/ac/site_libs/quarto-html/quarto.js"
      - "/ac/site_libs/quarto-html/tippy.umd.min.js"
      - "/ac/site_libs/quarto-nav/headroom.min.js"
      - "/ac/site_libs/quarto-nav/quarto-nav.js"
      - "/ac/site_libs/quarto-search/autocomplete.umd.js"
      - "/ac/site_libs/quarto-search/fuse.min.js"
      - "/ac/site_libs/quarto-search/quarto-search.js"
      - "/ac/r4ds.scss"

  pdf:
    documentclass: scrreprt
    fontfamily: "Arial"
    fontsize: 12pt

editor: visual
# font-path: "wss/fonts?families=SF+Pro,v3"
# fontfamily: "SF Pro Display"
# fontsize: 12px