name: Atualiza submodule

on:
  repository_dispatch:
    types: [submodule-books]


jobs:
  books:
    if: ${{ github.event.action == 'submodule-books' }}
    runs-on: ubuntu-latest
    environment:
      name: ENVIRONMENT
    env:
      USEREMAIL: ${{ secrets.USEREMAIL }}
      USERNAME: ${{ github.repository_owner }}
      TOKEN_REPO_SYNC: ${{ secrets.TOKEN_REPO_SYNC }}
    steps:
      - name: Checkout estatistica
        uses: actions/checkout@v4
        with:
          token: ${{ env.TOKEN_REPO_SYNC }}
          ref: main
          submodules: 'true'
          path: 'estatistica'

      - name: Atualiza submodule books
        run: |
          git config --global user.name "${{ env.USERNAME }}"
          git config --global user.email "${{ env.USEREMAIL }}"
          git submodule update --remote books
          git add books
          git commit -m "Atualiza books para última versão" || echo "Nada para commitar"
          git push