project:
  title: "CALCULO DE PROBABILIDADE"
  type: book
  resources: "./../../../"
  output-dir: "./../../MAT0075"
  lib-dir:  "./../delete/site_libs"
  post-render:  "./../include/post-render.py"
  preview:
    port: 4200
    browser: false

number-sections: false

book:
  chapters:
    - index.qmd
    - conteudo/1.espacoprob.qmd

    # - part: conteudo/1.espacoprob.qmd
    #   # chapters:
    #   #   - conteudo/1.1.subcaptulos.qmd

    - conteudo/references.qmd

bibliography: conteudo/references.bib

format:
  html:
    include-in-header: "./../include/include-in-head"
    toc: false
    sidebar: true
    theme:
      - cosmo
      - brand
    code-link: true
    search: true