project:
  type: default
  output-dir: "./../../docs/slide/"
  lib-dir: "./../../docs/ac/libs/"
  preview:
    timeout: 5
    host: "localhost"
    watch-inputs: true
    port: 4200
    browser: false

number-sections: false


format:
  revealjs:
    width: 1920
    height: 1080
    menu: false
    navigation-mode: linear
    transition: none
    transition-speed: slow
    background-transition: none
    slide-number: true
    show-slide-number: print
    css: 
      - "./../../docs/ac/styles/slide.css"