name: Hospedagem Hostinger

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 16 * 1"
  push:
    branches: ["main"]
    paths: [
        # Arquivos que disparam o workflow
        "**/*.html",
        "**/*.css",
        "**/*.js",
        "**/*.png",
        "**/*.jpeg",
        "**/*.jpg",
        "**/*.svg",
        "**/*.gif",
        "**/*.webp",
        "**/*.bmp",
        "**/*.ico",
        "**/*.woff",
        "**/*.woff2",
        "**/*.ttf",
        "**/*.eot",
        "**/*.otf",
        "**/*.json",
        "**/*.xml",
      ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo "Building the application"
  # Deploy desenvolvimento
  deploy-development:
    runs-on: ubuntu-latest
    environment:
      name: development
      url: ${{ vars.URL }}
    needs: build
    steps:
      - name: Repo Checkout
        uses: actions/checkout@v2
      - name: Hostinger Deployment
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rlgoDzvO --delete --checksum"
          SOURCE: "./"
          REMOTE_HOST: ${{ vars.REMOTE_HOST }}
          REMOTE_USER: ${{ vars.REMOTE_USER }}
          REMOTE_PORT: ${{ vars.REMOTE_PORT }}
          TARGET: ${{ vars.TARGET }}
  # Deploy staging
  deploy-staging:
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: ${{ vars.URL }}
    needs: deploy-development
    steps:
      - name: Repo Checkout
        uses: actions/checkout@v2
      - name: Hostinger Deployment
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rlgoDzvO --delete"
          SOURCE: "./"
          REMOTE_HOST: ${{ vars.REMOTE_HOST }}
          REMOTE_USER: ${{ vars.REMOTE_USER }}
          REMOTE_PORT: ${{ vars.REMOTE_PORT }}
          TARGET: ${{ vars.TARGET }}
  # Deploy produção
  deploy-production:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ vars.URL }}
    needs: deploy-staging
    steps:
      - name: Repo Checkout
        uses: actions/checkout@v2
      - name: Hostinger Deployment
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rlgoDzvO --delete"
          SOURCE: "./"
          REMOTE_HOST: ${{ vars.REMOTE_HOST }}
          REMOTE_USER: ${{ vars.REMOTE_USER }}
          REMOTE_PORT: ${{ vars.REMOTE_PORT }}
          TARGET: ${{ vars.TARGET }}
