name: Submodules e outras ações
# description: Atualiza submodules e outras ações relacionadas

on:
  workflow_dispatch:
  repository_dispatch:
    types: [submodule-books]

jobs:
  books:
    if: ${{ github.event.action == 'submodule-books' }}
    runs-on: ubuntu-latest
    environment:
      name: ENVIRONMENT
    env:
      USEREMAIL: ${{ secrets.USEREMAIL }}
      USERNAME: ${{ github.repository_owner }}
      TOKEN: ${{ secrets.TOKEN_REPO_SYNC }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout estatistica
        uses: actions/checkout@v4
        with:
          token: ${{ env.GITHUB_TOKEN }}
          ref: main
          path: "estatistica"
          submodules: "true"

      - name: Configura usuário do git
        run: |
          git config --global user.name "${{ env.USERNAME }}"
          git config --global user.email "${{ env.USEREMAIL }}"

      - name: Atualiza submodule books
        run: |
          git submodule update --remote books
          git add books

      - name: Verificar submodulo 'books'
        working-directory: estatistica/books
        run: |
          if [ cd books ]; then
            echo "Submodule 'books' updated successfully."
            git fetch
          else
            echo "Submodule 'books' update failed."
            exit 1
          fi

      - name: Detectar e salvar nomes dos livros alterados
        working-directory: estatistica/books
        run: |
          git fetch
          PASTAS=$(git diff --name-only HEAD @{u} \
            | grep -E '^build/[A-Z]{3}[0-9]{4}/.*\.(yml|qmd)$' \
            | sed -E 's|^(build/[A-Z]{3}[0-9]{4}).*|\1|' \
            | sort -u | tr '\n' ' ')
          echo "PASTAS_LIVROS_ALTERADOS=$PASTAS" >> $GITHUB_OUTPUT

      - name: Configura Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Versão do Quarto
        run: quarto --version 

      - name: Renderiza livros Modificados
        run: |

        # Renderiza livros Quarto

      - name: Limpa diretórios de 'libs'
        # Limpa diretórios de 'libs'

      - name: Configura Python
        # Configura Python

      - name: Instalar dependencias do Python
        # Instalar dependencias do Python

      - name: Corrigir links para GitHub Pages - Books
        # Corrigir links para GitHub Pages - Books

      - name: Sincronizar pasta 'artefatos_books' com 'estatistica/book'
        # Sincronizar pasta 'artefatos_books' com 'estatistica/book'

      # - name: Commitar alterações de 'estatistica/books'
      #   working-directory: estatistica
      #   run: |
      #     git add .
      #     git commit -m "Atualiza submodulos e aplica ações do workflow" || echo "Nada a commitar"
      #     git push origin main

      - name: Garante que a branch book existe e faz checkout
        # Garante que a branch book existe e faz checkout

      - name: Configura credenciais do Git
        # Configura credenciais do Git

      - name: Instala GitHub CLI
        # Instala GitHub CLI

      - name: Cria branch temporária para PR
        # Cria branch temporária para PR

      - name: Faz commit e push dos livros renderizados na branch temporária
        # Faz commit e push dos livros renderizados na branch temporária

      - name: Cria Pull Request para branch book
        # Cria Pull Request para branch book

